// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class CategoryFood
    {
        public CategoryFood()
        {
            Foods = new HashSet<Foods>();
        }

        public int CategoryFoodId { get; set; }
        public string TypeFood { get; set; }

        public virtual ICollection<Foods> Foods { get; set; }
    }
}