// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class Customers
    {
        public Customers()
        {
            OrdersDelivery = new HashSet<OrdersDelivery>();
        }

        public int CusId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Telephone { get; set; }
        public string Name { get; set; }

        public virtual ICollection<OrdersDelivery> OrdersDelivery { get; set; }
    }
}