// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class Details
    {
        public int DetailId { get; set; }
        public int? OrderDetailId { get; set; }
        public int? OptionsId { get; set; }
        public int? OptionsDetailId { get; set; }

        public virtual Options Options { get; set; }
        public virtual OptionsDetail OptionsDetail { get; set; }
        public virtual OderDetail OrderDetail { get; set; }
    }
}