// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class FoodOptions
    {
        public int FoodoptionId { get; set; }
        public int? FoodId { get; set; }
        public int? OptionsId { get; set; }

        public virtual Foods Food { get; set; }
        public virtual Options Options { get; set; }
    }
}