// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class ImageFood
    {
        public int ImageId { get; set; }
        public string Path { get; set; }
        public int? FoodId { get; set; }

        public virtual Foods Food { get; set; }
    }
}