// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class OderDetail
    {
        public OderDetail()
        {
            DetailsNavigation = new HashSet<Details>();
        }

        public int OrderdetailId { get; set; }
        public int? OrderId { get; set; }
        public int? FoodId { get; set; }
        public int? Quantity { get; set; }
        public int? Total { get; set; }
        public string Details { get; set; }
        public int? OrderdeliveryId { get; set; }

        public virtual Foods Food { get; set; }
        public virtual Orders Order { get; set; }
        public virtual OrdersDelivery Orderdelivery { get; set; }
        public virtual ICollection<Details> DetailsNavigation { get; set; }
    }
}