// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class OptionsDetail
    {
        public OptionsDetail()
        {
            Details = new HashSet<Details>();
        }

        public int OptionsDetailId { get; set; }
        public int? OptionsId { get; set; }
        public string Typename { get; set; }
        public bool? Status { get; set; }

        public virtual Options Options { get; set; }
        public virtual ICollection<Details> Details { get; set; }
    }
}