// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class OrdersDelivery
    {
        public OrdersDelivery()
        {
            OderDetail = new HashSet<OderDetail>();
            Payments = new HashSet<Payments>();
        }

        public int OrderDeliveryId { get; set; }
        public DateTime? DateIn { get; set; }
        public int? CusId { get; set; }
        public int? Total { get; set; }
        public int? StatusdeliveryId { get; set; }
        public string Details { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }

        public virtual Customers Cus { get; set; }
        public virtual StatusDelivery Statusdelivery { get; set; }
        public virtual ICollection<OderDetail> OderDetail { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
    }
}