// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackEndFlutter.Models.Data
{
    public partial class StatusDelivery
    {
        public StatusDelivery()
        {
            OrdersDelivery = new HashSet<OrdersDelivery>();
        }

        public int StatusdeliveryId { get; set; }
        public string Type { get; set; }

        public virtual ICollection<OrdersDelivery> OrdersDelivery { get; set; }
    }
}